export const GET_TOKEN_DATA = 'GET_TOKEN_DATA';
export const GET_TOKEN_DATA_LOADING = 'GET_TOKEN_DATA_LOADING';
export const GET_TOKEN_DATA_SUCCESS = 'GET_TOKEN_DATA_SUCCESS';
export const GET_TOKEN_DATA_ERROR = 'GET_TOKEN_DATA_ERROR';
export const TOGGLE_THEME = 'TOGGLE_THEME';
