const MenuItems = [
  {
    path: 'mint',
    key: 'mint',
    name: 'Mint',
    className: 'mint',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'savings',
    key: 'savings',
    name: 'Savings',
    className: 'savings',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'protocol',
    key: 'protocol',
    name: 'Protocol',
    className: 'protocol',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'borrow',
    key: 'borrow',
    name: 'Borrow',
    className: 'borrow',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'markets',
    key: 'markets',
    name: 'Markets',
    className: 'markets',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'docs',
    key: 'docs',
    name: 'Docs',
    className: 'docs',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
];

export default MenuItems;
