const MenuItems = [
  {
    path: 'mint',
    key: 'mint',
    name: 'Mint',
    className: 'mint',
    scrollSection: 'stablecoin-section-container',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'savings',
    key: 'savings',
    name: 'Savings',
    className: 'savings',
    scrollSection: 'earninterest-section-container',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'protocol',
    key: 'protocol',
    name: 'Protocol',
    className: 'protocol',
    scrollSection: 'protocolinfo-section-container',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'borrow',
    key: 'borrow',
    name: 'Borrow',
    className: 'borrow',
    scrollSection: 'borrow-on-demand-container',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  {
    path: 'markets',
    key: 'markets',
    name: 'Markets',
    className: 'markets',
    scrollSection: 'market-stats-info-wrapper',
    disabled: false,
    isNavigable: true,
    hidden: false,
    needAuth: true,
    children: [],
  },
  // {
  //   path: 'docs',
  //   key: 'docs',
  //   name: 'Docs',
  //   className: 'docs',
  //   scrollSection: '',
  //   disabled: false,
  //   isNavigable: true,
  //   hidden: false,
  //   needAuth: true,
  //   children: [],
  // },
];

export default MenuItems;
